name: Veriyi Public Reposa Yansıt

on:
  push:
    paths:
      - 'imla.txt'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Gizli repoyu klonla
      uses: actions/checkout@v3

    - name: Public reponu klonla ve güncelle
      run: |
        git config --global user.name "Enes Kalaycı Bot"
        git config --global user.email "bot@eneskalayci.dev"
        git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/eneskalaycidev/turkce-imla.git public
        cp imla.txt public/imla.txt
        cd public
        git add imla.txt
        git commit -m "imla.txt güncellendi: $(date '+%Y-%m-%d %H:%M:%S')" || echo "Değişiklik yok"
        git push
